name: CI - Build and Scan

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub (Optional if you push)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Backend Docker Image
      run: docker build -t backend:test ./app/backend

    - name: Build Frontend Docker Image
      run: docker build -t frontend:test ./app/frontend

    - name: Run Trivy on Backend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: backend:test
        format: table
        ignore-unfixed: true
        exit-code: 0

    - name: Run Trivy on Frontend Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: frontend:test
        format: table
        ignore-unfixed: true
        exit-code: 0
